image: archlinux/base

before_script:
  - pacman -Syyu --noconfirm
  - pacman -S help2man base-devel shellcheck git man-db --noconfirm --needed

build:
  stage: build
  script:
    - make VERSION=$(git describe --always)
    - sed -i "s|/etc/pacman-src.conf|bin/etc/pacman-src.conf|g" bin/pacman-src
  artifacts:
    paths:
      - bin/

shellcheck:
  stage: test
  script:
    - make check

test:
  stage: test
  script:
    - useradd tester -m
    - sudo --user=tester make test

man:
  stage: test
  script:
    - make install prefix=/usr
    - export MANPAGER=cat
    - man pacman-src
