before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y help2man

install:

  # Install a custom version of shellcheck instead of Travis CI's default
  - scversion="stable" 
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - shellcheck --version

script:
  - make
  - sudo make install prefix=/usr
  - shellcheck "$(which pacman-src)" -x
